from machine import Pin
import utime
led6 = Pin(25, Pin.OUT)
led2=Pin(16,Pin.OUT)
led=Pin(17,Pin.OUT)
led3=Pin(19,Pin.OUT)
led4=Pin(18,Pin.OUT)
led5=Pin(20,Pin.OUT)


while True:
    led5.value(1)
    utime.sleep(0.1)
    led5.value(0)
    utime.sleep(0.1)
    led4.value(1)
    utime.sleep(0.1)
    led4.value(0)
    utime.sleep(0.1)
    led3.value(1)
    utime.sleep(0.1)
    led3.value(0)
    utime.sleep(0.1)
    led.value(1)
    utime.sleep(0.1)
    led.value(0)
    utime.sleep(0.1)
    led2.value(1)
    utime.sleep(0.1)
    led2.value(0)
    utime.sleep(0.1)
    led6.value(1)
    utime.sleep(0.1)
    led6.value(0)
    utime.sleep(0.1)
    